#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\HomepageController::index

#last_article:
 #   path: /last
  #  controller: App\Controller\HomepageController::lastArticle

comment_edit:
  path: /comment/{id}/edit
  controller: App\Controller\CommentController::edit

comment_delete:
  path: /comment/{id}/delete
  controller: App\Controller\CommentController::delete

dashboard:
  path: /dashboard
  controller: App\Controller\HomepageController::dashboard

add:
  path: /add
  controller: App\Controller\HomepageController::add
