#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\HomepageController::index

last_article:
    path: /last
    controller: App\Controller\HomepageController::lastArticle

